from .auth import auth_bp
from .users import users_bp
from .students import students_bp
from .buildings import buildings_bp
from .rooms import rooms_bp
from .faces import faces_bp
from .access import access_bp
from .visitors import visitors_bp
from .alerts import alerts_bp
from .statistics import statistics_bp
